# Use official PostgreSQL image
FROM postgres:13

# Set environment variables
ENV POSTGRES_DB=wakeb_db
ENV POSTGRES_USER=wakeb_usr
ENV POSTGRES_PASSWORD=wakeb_pw

# Copy initialization scripts
COPY init-scripts/ /docker-entrypoint-initdb.d/

# Expose PostgreSQL port
EXPOSE 5432